
* glsim

The glsim project aims to provide a C++ class library to build
numerical simulation software.  The basic library consists of classes
that handle the cumbersome but essential administrative tasks that a
simulation program must perform.  There are also numerical routines
and analysis programs.

A couple of complete, full-working simulation programs are
distributed, but, although perhaps useful in themselves, they are
mainly intended as examples of the use of the libraries.  The aim of
the glsim project is not to provide a full-featured simulation program
using technique X, but to enable researchers to more easily produce
working simulation programs, by freeing them of the need to write code
for the housekeeping part of the simulation.

glsim's design, motivation and purpose have been described in the
following paper:

 - T. S. Grigera, /glsim: A general library for numerical
   simulation/.  Computer Physics Communications *182*, 2122-2131
   (2011). [[[http://www.sciencedirect.com/science/article/pii/S0010465511001597][URL]]] [[[doi:10.1016/j.cpc.2011.05.006][DOI]]]

There have been some interface and several implementation changes
since this publication leading to version 1.0, but it still remains a
valid reference.


* Contents

The package contains libraries, utilities and simulations, divided in
three thematic groups.

** Basic library

Includes classes for

  - error handling
  - interfacing to other basic libraries that provide useful services
    for simulations (random numbers, file manipulation, files in HDF5
    format, fast Fourier transform)
  - the main simulations abstractions as defined by glsim (parameters,
    environment, configuration, simulation, observables)

** Lattices and graphs

Provides template classes to represent various graphs and lattices
used in graph- or lattice- based simulations.

** Offlatice simulations

This library includes classes that provide:

 - representation off-lattice configurations and to save them (as
   single configurations or trajectories) in HDF5 files
 - computation of interactions of pairwise potentials
 - off-lattice simulations of particle systems:
   - Metropolis Monte Carlo
   - microcanonical (constant energy) Molecular Dynamics

Utilities:

 - creation and dumping of configurations in HDF5 format

Simulations:

 - canonical Molecular Dynamics of repulsive Lennard-Jones particles
 - Metropolis Monte Carlo of repulsive Lennard-Jones particles

** Analysis

This includes classes and utilities to perform various kinds of
analysis of simulation data.

Classes for:

 - Average and variance (with numerically accurate recurrence
   algorithm)
 - Histogram building
 - Time correlations with FFT

Utilities:

 - Average and variance
 - Geometric-window averaging of time series
 - Histogram building
 - Time correlations and relaxation time calculation


* Installation

If you download a tarball from a release (look for a =glsim-x.y.z.tar.gz= file
distributed only with the releases, check the release tab), you can
build with the traditional =configure= script: unpack, then run

: ./configure.sh
: make
: sudo make install

Or check the file INSTALL for detailed instructions.

If you clone the repository or download the source archives provided
by Github, you will not receive the =configure.sh= script, and you will need
=autotools= to generate it, as well as the correspondig
=Makefile.ini=.  With =autoconf=, =automake=, and =libtools=
installed, you do

: autoreconf
: libtoolize
: automake --add-missing
: autoreconf

and then you can run ~configure.sh~.

** Required libraries

=glsim= relies on several third-party libraries, which you will need
to install (note that in many Linux distributions, libraries are
distributed in separate development and run-time packages, you will
need both).  Packages required are:

 * GNU Scientific Library
 * Boost::system
 * Boost::program_options
 * Boost::serialization
 * Boost::date_time
 * Boost::timer
 * HDF5

** Recommended libraries and packages

 * FFTW3 (if not available, the FFT routines from GSL will be used)
 * Doxygen (if you want to build documentation)
 * LaTeX (for the Postscript or PDF documentation)


* Documentation


glsim documentation is transitioning from a literate progamming
paradigm using Noweb to in-code documentation with Doxygen.  Doing

: make doc

will generate the LaTeX and HTML documentation (still not complete).
It is not currently being installed, you can find it in the doc
directory. 


* Obtaining GLSIM

glsim is hosted by [[https://github.com/tgrigera/glsim][GitHub (tgrigera/glsim)]].


* Author

glsim is written and maintained by Tomas S. Grigera at the University
of La Plata. He can be contacted by e-mail at
~tgrigera@iflysib.unlp.edu.ar~.


* Copyright statements and licensing terms

glsim is copyright (C) 2009--2015 by Tomas S. Grigera.

glsim is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License (GPL) as published by the
Free Software Foundation, with the additional requirements of
attribution and nonmisrepresentation. You can use either version 3, or
(at your option) any later version.

Additional terms under GNU GPL version 3 section 7:

When you redistribute this software, you are required to preserve its
author attributions.  If you distribute verbatim copies, you must not
alter the AUTHORS file or attributions inserted in the source files,
and you must not change the software's name.  If you distribute a
modified copy, then you must give clear notice that your work is
different from but based on glsim.  You must distribute it under a
different name, but include a prominent notice specifying that "(your
package) is based on glsim version x.x", and provide a pointer to the
glsim distribution.

If you use glsim to produced published work, please cite us:

 - T. S. Grigera, /glsim: A general library for numerical
   simulation/.  Computer Physics Communications *182*, 2122-2131
   (2011).

glsim is distributed in the hope that it will be useful, but WITHOUT
ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
or FITNESS FOR A PARTICULAR PURPOSE.

For details see the file LICENSE in the home directory. If the file is
missing, contact the maintainers.
